export function createWorldFeatureCoordinator({ getFrontier, getSurvival, mapRuntime = null, getQuickUseItemId }) {
  let activeMapRuntime = mapRuntime;
  const call = (getTarget, method, ...args) => getTarget()[method](...args);
  const frontierCall = (method, ...args) => call(getFrontier, method, ...args);
  const survivalCall = (method, ...args) => call(getSurvival, method, ...args);
  const mapCall = (method, ...args) => activeMapRuntime[method](...args);
  return {
    setMapRuntime(nextRuntime) { activeMapRuntime = nextRuntime; },
    frontier: new Proxy({}, { get: (_target, method) => (...args) => call(getFrontier, method, ...args) }),
    survival: new Proxy({}, { get: (_target, method) => (...args) => call(getSurvival, method, ...args) }),
    map: {
      registerGate: (...args) => mapCall("registerMapGate", ...args),
      registerConnectorTunnel: (...args) => mapCall("registerConnectorTunnelZone", ...args),
      findTriggeredGate: () => mapCall("findTriggeredGate"),
      updateCurrentMap: () => mapCall("updateCurrentMap"),
      isInConnectorTunnel: () => mapCall("isInConnectorTunnel"),
      getEffectiveAirMapId: () => mapCall("getEffectiveAirMapId"),
    },
    getFrontierShopPurchaseFeedback: (...args) => frontierCall("getShopPurchaseFeedback", ...args),
    getFrontierShopOperation: (...args) => frontierCall("getShopOperation", ...args),
    getFrontierDisplayOperation: (...args) => frontierCall("getDisplayOperation", ...args),
    assignFrontierDisplayEntry: (...args) => frontierCall("assignDisplayEntry", ...args),
    clearFrontierDisplayEntry: (...args) => frontierCall("clearDisplayEntry", ...args),
    getFrontierShopAssignedWallet: (...args) => frontierCall("getShopAssignedWallet", ...args),
    getFrontierShopSellerWallet: (...args) => frontierCall("getShopSellerWallet", ...args),
    isFrontierShopSeller: (...args) => frontierCall("isShopSeller", ...args),
    canManageFrontierShopSlot: (...args) => frontierCall("canManageShopSlot", ...args),
    canUseFrontierShopSlot: (...args) => frontierCall("canUseShopSlot", ...args),
    canEditFrontierShopListing: (...args) => frontierCall("canEditShopListing", ...args),
    canManageFrontierShopSellerTools: (...args) => frontierCall("canManageShopSellerTools", ...args),
    canRegisterFrontierShopListing: (...args) => frontierCall("canRegisterShopListing", ...args),
    canCollectFrontierShopSettlement: (...args) => frontierCall("canCollectShopSettlement", ...args),
    getFrontierDisplayAssignedWallet: (...args) => frontierCall("getDisplayAssignedWallet", ...args),
    canManageFrontierDisplaySlot: (...args) => frontierCall("canManageDisplaySlot", ...args),
    canUseFrontierDisplaySlot: (...args) => frontierCall("canUseDisplaySlot", ...args),
    getFrontierBoothInteractionPlan: (...args) => frontierCall("getBoothInteractionPlan", ...args),
    collectFrontierShopSettlement: (...args) => frontierCall("collectShopSettlement", ...args),
    assignFrontierDisplaySlotUser: (...args) => frontierCall("assignDisplaySlotUser", ...args),
    clearFrontierDisplaySlotUser: (...args) => frontierCall("clearDisplaySlotUser", ...args),
    getCurrentFrontierParcelLabel: () => frontierCall("getCurrentParcelLabel"),
    getSelectedFrontierParcelLabel: () => frontierCall("getSelectedParcelLabel"),
    getFrontierBuildState: (...args) => frontierCall("getBuildState", ...args),
    getFrontierParcelSafeStandingPoint: (...args) => frontierCall("getSafeStandingPoint", ...args),
    rebuildAllFrontierConstructionVisuals: () => frontierCall("rebuildAllConstructionVisuals"),
    getFrontierNextStageConfig: (...args) => frontierCall("getNextStageConfig", ...args),
    rebuildFrontierParcelConstructionVisual: (...args) => frontierCall("rebuildParcelConstructionVisual", ...args),
    renderFrontierBuildWindow: () => frontierCall("renderBuildWindow"),
    setFrontierBuildOpen: (...args) => frontierCall("setBuildOpen", ...args),
    openFrontierShopRegisterDialog: (...args) => frontierCall("openShopRegisterDialog", ...args),
    closeFrontierShopRegisterDialog: () => frontierCall("closeShopRegisterDialog"),
    clearFrontierShopListing: (...args) => frontierCall("clearShopListing", ...args),
    tryPurchaseFrontierShopListing: (...args) => frontierCall("purchaseShopListing", ...args),
    commitFrontierShopListing: () => frontierCall("commitShopListing"),
    renderFrontierShopRegisterDialog: () => frontierCall("renderShopRegisterDialog"),
    assignFrontierShopSlotUser: (...args) => frontierCall("assignShopSlotUser", ...args),
    clearFrontierShopSlotUser: (...args) => frontierCall("clearShopSlotUser", ...args),
    updateFrontierShopListingPrice: (...args) => frontierCall("updateShopListingPrice", ...args),
    tryAdvanceFrontierBuildStage: () => frontierCall("tryAdvanceBuildStage"),
    saveFrontierBuildSignText: () => frontierCall("saveBuildSignText"),
    closeFrontierBoothDialog: () => frontierCall("closeBoothDialog"),
    renderFrontierBoothDialog: () => frontierCall("renderBoothDialog"),
    openFrontierBoothDialog: (parcelLabel, slotKey, boothTitle, mode) => frontierCall("openBoothDialog", { parcelLabel, slotKey, boothTitle, mode }),
    setForgeOpen: (...args) => survivalCall("setForgeOpen", ...args),
    setRefineryOpen: (...args) => survivalCall("setRefineryOpen", ...args),
    renderRefineryWindow: () => survivalCall("renderRefineryWindow"),
    tryCraftSelectedRefineryRecipe: () => survivalCall("tryCraftSelectedRefineryRecipe"),
    renderForgeWindow: () => survivalCall("renderForgeWindow"),
    tryUpgradeEquippedItem: () => survivalCall("tryUpgradeEquippedItem"),
    useQuickUseItem: (key) => survivalCall("useQuickUseItem", key, getQuickUseItemId),
  };
}
