import {
  QUICK_USE_ALLOWED_KEYS,
  INVENTORY_STACK_LIMIT,
  createItemDefs,
  getDevMaterialItemIds,
  getDevBulkGrantItemIds,
  createInventoryEntryInstanceId,
  getInventoryStackMax,
  createInventorySlotEntry,
  normalizeInventorySlotEntry,
  createEquippedItemRef,
  normalizeEquippedItemRef,
  getSlotItemId,
  getSlotItemCount,
  isNftInventoryEntry,
  isSameInventoryEntryAsEquipped,
  getInventoryEntryCategory,
  getInventoryEntryEquipSlot,
  getInventoryEntryDisplayName,
  getInventoryEntryDisplayIcon,
  getInventoryEntryTooltipData,
} from "./items.js";
import {
  createInitialInventoryState,
  createInitialPersonalStorageState,
  createQuickUseBinding,
  normalizeQuickUseBinding,
  getQuickUseBinding,
  getQuickUseItemId,
  getQuickUseKeyForItemId,
  assignQuickUseKeyToItem,
  findFirstEmptySlot,
} from "./inventory.js";
import {
  PICKAXE_UPGRADE_LEVELS,
  clampPickaxeLevel,
  getCurrentPickaxeStats,
  getNextPickaxeUpgrade,
  getForgeUpgradeStateData,
  getMiningPowerForTool,
} from "./mining.js";
import { createInventoryRuntime } from "./inventoryRuntime.js";
import { createInventoryFacade } from "./inventoryFacade.js";
import { createInventoryGameplayController } from "../ui/inventoryGameplayController.js";
import { createInventoryPresentationController } from "../ui/inventoryPresentationController.js";
import { createInventoryIntegrationController } from "../ui/inventoryIntegrationController.js";

const ALWAYS_DROP_BLOCKED_ITEM_IDS = new Set(["abandonedMineKey"]);
const TUTORIAL_DROP_BLOCKED_ITEM_IDS = new Set(["pickaxe", "safetyHelmet"]);

export function createInventoryFeatureCoordinator(ctx) {
  const inventory = createInitialInventoryState();
  const personalStorage = createInitialPersonalStorageState();
  let gameplayController = null;
  let integrationController = null;

  const itemDefs = createItemDefs({
    ...ctx.itemModelBuilders,
    getPickaxeLevel: () => inventory.pickaxeLevel,
  });

  function isQuestCriticalEntry(entry) {
    const itemId = getSlotItemId(entry);
    if (!itemId) return false;
    if (ALWAYS_DROP_BLOCKED_ITEM_IDS.has(itemId)) return true;
    return !ctx.isTutorialComplete() && TUTORIAL_DROP_BLOCKED_ITEM_IDS.has(itemId);
  }

  let facade = null;
  const runtime = createInventoryRuntime({
    inventory,
    personalStorage,
    itemDefs,
    getSlotItemId,
    getSlotItemCount,
    isNftInventoryEntry,
    normalizeInventorySlotEntry: (entry) => facade.normalizeSlot(entry),
    normalizeEquippedItemRef: (entry) => facade.normalizeEquippedRef(entry),
    createInventorySlotEntry: (itemId, count, extra) => facade.createSlot(itemId, count, extra),
    createEquippedItemRef,
    getInventoryStackMax: (itemId) => facade.getStackMax(itemId),
    getInventoryEntryEquipSlot: (entry) => facade.getEntryEquipSlot(entry),
    isSameInventoryEntryAsEquipped,
    isQuestCriticalItemBlockedFromDiscard: isQuestCriticalEntry,
    getQuickUseAssignState: ctx.getQuickUseAssignState,
    setQuickUseAssignState: ctx.setQuickUseAssignState,
    onCreditsChanged: ctx.onCreditsChanged,
  });

  facade = createInventoryFacade({
    inventory,
    personalStorage,
    itemDefs,
    runtime,
    stackLimit: INVENTORY_STACK_LIMIT,
    quickUseKeys: QUICK_USE_ALLOWED_KEYS,
    getDevMaterialItemIds,
    getDevBulkGrantItemIds,
    createEntryInstanceId: createInventoryEntryInstanceId,
    getStackMax: getInventoryStackMax,
    createSlot: createInventorySlotEntry,
    normalizeSlot: normalizeInventorySlotEntry,
    createEquippedRef: createEquippedItemRef,
    normalizeEquippedRef: normalizeEquippedItemRef,
    getEntryCategory: getInventoryEntryCategory,
    getEntryEquipSlot: getInventoryEntryEquipSlot,
    getEntryName: getInventoryEntryDisplayName,
    getEntryIcon: getInventoryEntryDisplayIcon,
    getEntryTooltipData: getInventoryEntryTooltipData,
    createQuickUseBinding,
    normalizeQuickUseBinding,
    getQuickUseBinding,
    getQuickUseItemId,
    getQuickUseKeyForItemId,
    getCurrentPickaxeStats: (level) => getCurrentPickaxeStats(level, PICKAXE_UPGRADE_LEVELS),
    getNextPickaxeUpgrade: (level) => getNextPickaxeUpgrade(level, PICKAXE_UPGRADE_LEVELS),
    getForgeUpgradeState: getForgeUpgradeStateData,
    getMiningPower: getMiningPowerForTool,
    findFirstEmptySlot,
    getSlotItemId,
    isNftEntry: isNftInventoryEntry,
    isSameAsEquipped: isSameInventoryEntryAsEquipped,
    clampPickaxeLevel: (level) => clampPickaxeLevel(level, PICKAXE_UPGRADE_LEVELS),
    isQuestCritical: isQuestCriticalEntry,
    randRange: ctx.randomRange,
    syncCredits: () => {},
  });

  const presentationController = createInventoryPresentationController({
    THREE: ctx.THREE,
    itemDefs,
    getPickaxeLevel: () => inventory.pickaxeLevel,
    getSlotItemId,
    isNftEntry: isNftInventoryEntry,
    getEntryName: facade.getEntryName,
    getEntryIcon: facade.getEntryIcon,
    buildPickaxeModel: ctx.itemModelBuilders.buildPickaxeModel,
    buildSafetyHelmetModel: ctx.itemModelBuilders.buildSafetyHelmetModel,
  });

  function updateInventoryUi() {
    integrationController?.updateInventoryUi();
  }

  gameplayController = createInventoryGameplayController({
    inventory,
    personalStorage,
    inventoryRuntime: runtime,
    inventoryUiController: ctx.inventoryUiController,
    quickUseAllowedKeys: QUICK_USE_ALLOWED_KEYS,
    itemDefs,
    ui: ctx.ui,
    getSlotItemId,
    getSlotItemCount,
    getEntryCategory: facade.getEntryCategory,
    getEntryName: facade.getEntryName,
    getEntryTooltipData: facade.getEntryTooltip,
    getEntryEquipSlot: facade.getEntryEquipSlot,
    getEntryVisual: presentationController.createEntryVisual,
    getDisplayResolvedEntry: facade.resolveDisplayEntry,
    normalizeInventorySlotEntry: facade.normalizeSlot,
    createInventorySlotEntry: facade.createSlot,
    createEquippedItemRef: facade.createEquippedRef,
    getEquippedItemRef: facade.getEquippedRef,
    getEquippedItem: facade.getEquippedItem,
    setEquippedItem: facade.setEquippedRef,
    isNftEntry: isNftInventoryEntry,
    isSameAsEquipped: isSameInventoryEntryAsEquipped,
    isQuickUseAssignableItemId: (itemId) => itemId === "freshAirCanister",
    getQuickUseItemId: facade.getQuickUseItemId,
    getQuickUseKeyForItemId: facade.getQuickUseKeyForItemId,
    assignQuickUseKeyToItem: (itemId, key) => assignQuickUseKeyToItem(inventory, itemId, key, QUICK_USE_ALLOWED_KEYS),
    getQuickUseAssignState: ctx.getQuickUseAssignState,
    setQuickUseAssignState: ctx.setQuickUseAssignState,
    isBuildPartItemId: ctx.isBuildPartItemId,
    isFencePlacementMode: ctx.isFencePlacementMode,
    getSelectedStructureItemId: ctx.getSelectedStructureItemId,
    makeSlot: ctx.makeSlot,
    setTabStyles: ctx.setTabStyles,
    showTooltip: ctx.showTooltip,
    hideTooltip: ctx.hideTooltip,
    showMessage: ctx.showMessage,
    updateInventoryUi,
    refreshQuestProgress: ctx.refreshQuestProgress,
    schedulePlayerSave: ctx.schedulePlayerSave,
    closeFrontierBuild: ctx.closeFrontierBuild,
    useFreshAirCanister: ctx.useFreshAirCanister,
    toggleFencePlacementMode: ctx.toggleFencePlacementMode,
    toggleStructurePlacement: ctx.toggleStructurePlacement,
    setLastMessageUntil: ctx.setLastMessageUntil,
  });

  integrationController = createInventoryIntegrationController({
    ...ctx.integration,
    disposeObject: presentationController.disposeObject,
    getEquippedItemRef: facade.getEquippedRef,
    getEquippedItem: facade.getEquippedItem,
    getEquippedToolId: facade.getEquippedToolId,
    getEquippedPickaxeLevel: facade.getEquippedPickaxeLevel,
    pruneQuickUseBindings: gameplayController.pruneQuickUseBindings,
    renderPersonalStorageWindow: gameplayController.renderPersonalStorageWindow,
    renderInventoryWindow: gameplayController.renderInventoryWindow,
  });

  const equipmentPreview = integrationController.initializePreview({
    ...ctx.preview,
    getEquippedItemRef: facade.getEquippedRef,
    getEquippedItem: facade.getEquippedItem,
    getDisplayResolvedEntry: facade.resolveDisplayEntry,
    getEntryName: facade.getEntryName,
    getEntryVisual: presentationController.createEntryVisual,
    isNftEntry: isNftInventoryEntry,
    getEquippedToolId: facade.getEquippedToolId,
    getEquippedPickaxeLevel: facade.getEquippedPickaxeLevel,
    unequipSlot: gameplayController.unequipSlot,
  });

  return {
    inventory,
    personalStorage,
    itemDefs,
    runtime,
    facade,
    presentationController,
    gameplayController,
    integrationController,
    equipmentPreview,
    equipment: integrationController.equipment,
    getDevMaterialItemIds: facade.getDevMaterialItemIds,
    getDevBulkGrantItemIds: facade.getDevBulkGrantItemIds,
    createInventoryEntryInstanceId: facade.createEntryInstanceId,
    getInventoryStackMax: facade.getStackMax,
    createInventorySlotEntry: facade.createSlot,
    addInventoryEntry: facade.addEntry,
    normalizeInventorySlotEntry: facade.normalizeSlot,
    createEquippedItemRef: facade.createEquippedRef,
    normalizeEquippedItemRef: facade.normalizeEquippedRef,
    getInventoryEntryCategory: facade.getEntryCategory,
    getInventoryEntryEquipSlot: facade.getEntryEquipSlot,
    getEquippedInventoryEntry: facade.getEquippedEntry,
    getDisplayResolvedInventoryEntry: facade.resolveDisplayEntry,
    getResolvedPickaxeLevel: facade.getResolvedPickaxeLevel,
    getEquippedPickaxeLevel: facade.getEquippedPickaxeLevel,
    getInventoryEntryDisplayName: facade.getEntryName,
    getInventoryEntryDisplayIcon: facade.getEntryIcon,
    getInventoryEntryTooltipData: facade.getEntryTooltip,
    createQuickUseBinding: facade.createQuickUseBinding,
    normalizeQuickUseBinding: facade.normalizeQuickUseBinding,
    getQuickUseBinding: facade.getQuickUseBinding,
    getQuickUseItemId: facade.getQuickUseItemId,
    getQuickUseKeyForItemId: facade.getQuickUseKeyForItemId,
    pruneQuickUseBindings: gameplayController.pruneQuickUseBindings,
    getCurrentPickaxeStats: facade.getCurrentPickaxeStats,
    getEquippedToolId: facade.getEquippedToolId,
    getNextPickaxeUpgrade: facade.getNextPickaxeUpgrade,
    getForgeTargetItemId: facade.getForgeTargetItemId,
    getForgeUpgradeState: facade.getForgeUpgradeState,
    getEquippedMiningPower: facade.getEquippedMiningPower,
    findInventorySlotIndexByEntry: facade.findInventorySlotIndex,
    getInventorySlotEntryByEntry: facade.getInventorySlotEntry,
    clampPlayerCredits: facade.clampCredits,
    getPlayerCredits: facade.getCredits,
    setPlayerCredits: facade.setCredits,
    grantPlayerCredits: facade.grantCredits,
    canAffordPlayerCredits: facade.canAffordCredits,
    spendPlayerCredits: facade.spendCredits,
    formatPlayerCreditsLabel: (value = facade.getCredits()) => `${ctx.currencyName}: ${facade.clampCredits(value)}원`,
    isQuestCriticalItemBlockedFromDiscard: isQuestCriticalEntry,
    canDiscardInventoryEntry: runtime.canDiscard,
    canMoveInventoryEntryToPersonalStorage: runtime.canStore,
    findFirstEmptyStorageSlot: facade.findFirstEmptyStorageSlot,
    addEntryToStorage: facade.addEntryToStorage,
    addEntryToInventory: facade.addEntryToInventory,
    moveInventoryEntryToStorage: facade.moveToStorage,
    moveStorageEntryToInventory: facade.moveToInventory,
    closeDiscardDialog: gameplayController.closeDiscardDialog,
    openDiscardDialog: gameplayController.openDiscardDialog,
    commitDiscardDialog: gameplayController.commitDiscardDialog,
    findFirstSlotWithItem: facade.findFirstSlotWithItem,
    getItemCount: facade.getItemCount,
    findFirstEmptySlot: facade.findFirstEmptySlot,
    addItem: facade.addItem,
    consumeItem: facade.consumeItem,
    hasEquippedTool: (itemId) => facade.getEquippedItem("tool") === itemId,
    hasItem: facade.hasItem,
    syncEquippedToolGroupModel: integrationController.syncToolGroupModel,
    refreshEquippedPickaxeModel: integrationController.refreshToolModel,
    updateEquippedVisual: integrationController.updateEquipmentVisibility,
    getEquippedItemRef: facade.getEquippedRef,
    getEquippedItemForSlot: facade.getEquippedItem,
    setEquippedItem: facade.setEquippedRef,
    equipFirstOwnedInventoryItem: facade.equipFirstOwnedItem,
    toggleEquipItem: gameplayController.toggleEquipItem,
    beginQuickUseAssignment: gameplayController.beginQuickUseAssignment,
    cancelQuickUseAssignment: gameplayController.cancelQuickUseAssignment,
    clearQuickUseAssignmentForEntry: gameplayController.clearQuickUseAssignmentForEntry,
    commitQuickUseAssignment: gameplayController.commitQuickUseAssignment,
    unequipSlot: gameplayController.unequipSlot,
    resizeEquipmentPreview: integrationController.resizePreview,
    renderEquipmentPreview: integrationController.renderPreview,
    renderEquipmentWindow: integrationController.renderEquipmentWindow,
    updateInventoryUI: updateInventoryUi,
    createItemVisualElement: presentationController.createItemVisual,
    createInventoryEntryVisualElement: presentationController.createEntryVisual,
    createForgeUpgradeVisualElement: presentationController.createForgeUpgradeVisual,
  };
}
